//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZ_Konfigurator.Resources.Localization.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue To Exterior.
        /// </summary>
        internal static string AccessoriesView_ContinueToExterior_Button {
            get {
                return ResourceManager.GetString("AccessoriesView_ContinueToExterior_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesView_Title {
            get {
                return ResourceManager.GetString("AccessoriesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistence Systems.
        /// </summary>
        internal static string AccessoryCategory_AssistenceSystems {
            get {
                return ResourceManager.GetString("AccessoryCategory_AssistenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        internal static string AccessoryCategory_Comfort {
            get {
                return ResourceManager.GetString("AccessoryCategory_Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotainment.
        /// </summary>
        internal static string AccessoryCategory_Infotainment {
            get {
                return ResourceManager.GetString("AccessoryCategory_Infotainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology and Safety.
        /// </summary>
        internal static string AccessoryCategory_TechnologyAndSafety {
            get {
                return ResourceManager.GetString("AccessoryCategory_TechnologyAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string ConfigurationLayout_Accessories_Button {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Accessories_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        internal static string ConfigurationLayout_BasePrice_Label {
            get {
                return ResourceManager.GetString("ConfigurationLayout_BasePrice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        internal static string ConfigurationLayout_EngineSettings_Button {
            get {
                return ResourceManager.GetString("ConfigurationLayout_EngineSettings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ConfigurationLayout_Exterior_Button {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Exterior_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string ConfigurationLayout_ExtrasPrice_Label {
            get {
                return ResourceManager.GetString("ConfigurationLayout_ExtrasPrice_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to model selection.
        /// </summary>
        internal static string ConfigurationLayout_GoToModelOverview {
            get {
                return ResourceManager.GetString("ConfigurationLayout_GoToModelOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Overview.
        /// </summary>
        internal static string ConfigurationLayout_GoToOverview {
            get {
                return ResourceManager.GetString("ConfigurationLayout_GoToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string ConfigurationLayout_Overview_Extras_Header {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Overview_Extras_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        internal static string ConfigurationLayout_Overview_Paint_Header {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Overview_Paint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rims.
        /// </summary>
        internal static string ConfigurationLayout_Overview_Rims_Header {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Overview_Rims_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ConfigurationLayout_Price_Label {
            get {
                return ResourceManager.GetString("ConfigurationLayout_Price_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string ConfigurationOverviewView_Accessories_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Accessories_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        internal static string ConfigurationOverviewView_BasePrice_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_BasePrice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ConfigurationOverviewView_Exterior_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Exterior_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras Price.
        /// </summary>
        internal static string ConfigurationOverviewView_ExtrasPrice_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_ExtrasPrice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ConfigurationOverviewView_FinalPrice_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_FinalPrice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Configuration.
        /// </summary>
        internal static string ConfigurationOverviewView_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Your Configuration.
        /// </summary>
        internal static string ConfigurationOverviewView_Order_Button {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Order_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription (optional).
        /// </summary>
        internal static string ConfigurationOverviewView_OrderDescription_Placeholder {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_OrderDescription_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        internal static string ConfigurationOverviewView_Paint_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Paint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string ConfigurationOverviewView_PlaceOrder_Button {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_PlaceOrder_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rims.
        /// </summary>
        internal static string ConfigurationOverviewView_Rims_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Rims_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Data.
        /// </summary>
        internal static string ConfigurationOverviewView_TechnicalData_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_TechnicalData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Overview.
        /// </summary>
        internal static string ConfigurationOverviewView_Title {
            get {
                return ResourceManager.GetString("ConfigurationOverviewView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDI.
        /// </summary>
        internal static string EngineCategory_TDI {
            get {
                return ResourceManager.GetString("EngineCategory_TDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFSI.
        /// </summary>
        internal static string EngineCategory_TFSI {
            get {
                return ResourceManager.GetString("EngineCategory_TFSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue To Accessories.
        /// </summary>
        internal static string EngineSettingsView_ContinueToAccessories_Button {
            get {
                return ResourceManager.GetString("EngineSettingsView_ContinueToAccessories_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Settings.
        /// </summary>
        internal static string EngineSettingsView_Title {
            get {
                return ResourceManager.GetString("EngineSettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue To Overview.
        /// </summary>
        internal static string ExteriorView_ContinueToOverview_Button {
            get {
                return ResourceManager.GetString("ExteriorView_ContinueToOverview_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        internal static string ExteriorView_Paints_Header {
            get {
                return ResourceManager.GetString("ExteriorView_Paints_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rims.
        /// </summary>
        internal static string ExteriorView_Rims_Header {
            get {
                return ResourceManager.GetString("ExteriorView_Rims_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorView_Title {
            get {
                return ResourceManager.GetString("ExteriorView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string FuelCategory_Diesel {
            get {
                return ResourceManager.GetString("FuelCategory_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        internal static string FuelCategory_Petrol {
            get {
                return ResourceManager.GetString("FuelCategory_Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string FuelKind_Diesel {
            get {
                return ResourceManager.GetString("FuelKind_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        internal static string FuelKind_Petrol {
            get {
                return ResourceManager.GetString("FuelKind_Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string General_From {
            get {
                return ResourceManager.GetString("General_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Configurator.
        /// </summary>
        internal static string General_ProductTitle {
            get {
                return ResourceManager.GetString("General_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        internal static string General_RimSizeUnit {
            get {
                return ResourceManager.GetString("General_RimSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string General_View {
            get {
                return ResourceManager.GetString("General_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design your individual car by configuring each and every part of it.
        /// </summary>
        internal static string HomeView_ConfigurationDescription {
            get {
                return ResourceManager.GetString("HomeView_ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Configuration.
        /// </summary>
        internal static string HomeView_StartConfiguration_Button {
            get {
                return ResourceManager.GetString("HomeView_StartConfiguration_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Layout_Home_Link {
            get {
                return ResourceManager.GetString("Layout_Home_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Layout_OrderList_Link {
            get {
                return ResourceManager.GetString("Layout_OrderList_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your model.
        /// </summary>
        internal static string ModelView_Header {
            get {
                return ResourceManager.GetString("ModelView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string ModelView_Title {
            get {
                return ResourceManager.GetString("ModelView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        internal static string OrderListView_BasePrice_Header {
            get {
                return ResourceManager.GetString("OrderListView_BasePrice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string OrderListView_CarModel_Header {
            get {
                return ResourceManager.GetString("OrderListView_CarModel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string OrderListView_Description_Header {
            get {
                return ResourceManager.GetString("OrderListView_Description_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string OrderListView_ExstrasPrice_Header {
            get {
                return ResourceManager.GetString("OrderListView_ExstrasPrice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string OrderListView_Header {
            get {
                return ResourceManager.GetString("OrderListView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string OrderListView_Price_Header {
            get {
                return ResourceManager.GetString("OrderListView_Price_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Overview.
        /// </summary>
        internal static string OrderListView_Title {
            get {
                return ResourceManager.GetString("OrderListView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy a link to your order.
        /// </summary>
        internal static string OrderOverviewView_CopyOrderLink_Button {
            get {
                return ResourceManager.GetString("OrderOverviewView_CopyOrderLink_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        internal static string OrderOverviewView_Header {
            get {
                return ResourceManager.GetString("OrderOverviewView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the overview to the configuration you ordered.
        /// </summary>
        internal static string OrderOverviewView_OrderSuccessful_Description_1 {
            get {
                return ResourceManager.GetString("OrderOverviewView_OrderSuccessful_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also .
        /// </summary>
        internal static string OrderOverviewView_OrderSuccessful_Description_2 {
            get {
                return ResourceManager.GetString("OrderOverviewView_OrderSuccessful_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to view it later.
        /// </summary>
        internal static string OrderOverviewView_OrderSuccessful_Description_3 {
            get {
                return ResourceManager.GetString("OrderOverviewView_OrderSuccessful_Description_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order successfully placed.
        /// </summary>
        internal static string OrderOverviewView_OrderSuccessful_Header {
            get {
                return ResourceManager.GetString("OrderOverviewView_OrderSuccessful_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Overview.
        /// </summary>
        internal static string OrderOverviewView_Title {
            get {
                return ResourceManager.GetString("OrderOverviewView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic.
        /// </summary>
        internal static string PaintCategory_Metalic {
            get {
                return ResourceManager.GetString("PaintCategory_Metalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearlescent.
        /// </summary>
        internal static string PaintCategory_Pearlescent {
            get {
                return ResourceManager.GetString("PaintCategory_Pearlescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uni.
        /// </summary>
        internal static string PaintCategory_Uni {
            get {
                return ResourceManager.GetString("PaintCategory_Uni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration 0-100 km/h.
        /// </summary>
        internal static string TechnicalData_Acceleration {
            get {
                return ResourceManager.GetString("TechnicalData_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        internal static string TechnicalData_Consumption {
            get {
                return ResourceManager.GetString("TechnicalData_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissions.
        /// </summary>
        internal static string TechnicalData_Emissions {
            get {
                return ResourceManager.GetString("TechnicalData_Emissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Size.
        /// </summary>
        internal static string TechnicalData_EngineSize {
            get {
                return ResourceManager.GetString("TechnicalData_EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        internal static string TechnicalData_FuelType {
            get {
                return ResourceManager.GetString("TechnicalData_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Performance.
        /// </summary>
        internal static string TechnicalData_Performance {
            get {
                return ResourceManager.GetString("TechnicalData_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed.
        /// </summary>
        internal static string TechnicalData_TopSpeed {
            get {
                return ResourceManager.GetString("TechnicalData_TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string TechnicalData_Transmission {
            get {
                return ResourceManager.GetString("TechnicalData_Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Gear.
        /// </summary>
        internal static string TechnicalData_Transmission_Suffix {
            get {
                return ResourceManager.GetString("TechnicalData_Transmission_Suffix", resourceCulture);
            }
        }
    }
}
