//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZ_Konfigurator.Resources.Localization.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesHeader {
            get {
                return ResourceManager.GetString("AccessoriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesTitle {
            get {
                return ResourceManager.GetString("AccessoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistence Systems.
        /// </summary>
        internal static string AccessoryCategory_AssistenceSystems {
            get {
                return ResourceManager.GetString("AccessoryCategory_AssistenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        internal static string AccessoryCategory_Comfort {
            get {
                return ResourceManager.GetString("AccessoryCategory_Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotainment.
        /// </summary>
        internal static string AccessoryCategory_Infotainment {
            get {
                return ResourceManager.GetString("AccessoryCategory_Infotainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology and Safety.
        /// </summary>
        internal static string AccessoryCategory_TechnologyAndSafety {
            get {
                return ResourceManager.GetString("AccessoryCategory_TechnologyAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design your individual car by configuring each and every part of it.
        /// </summary>
        internal static string ConfigurationDescription {
            get {
                return ResourceManager.GetString("ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        internal static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission.
        /// </summary>
        internal static string Emission {
            get {
                return ResourceManager.GetString("Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        internal static string EngineSettingsHeader {
            get {
                return ResourceManager.GetString("EngineSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Settings.
        /// </summary>
        internal static string EngineSettingsTitle {
            get {
                return ResourceManager.GetString("EngineSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorHeader {
            get {
                return ResourceManager.GetString("ExteriorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorTitle {
            get {
                return ResourceManager.GetString("ExteriorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string Gears {
            get {
                return ResourceManager.GetString("Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your model.
        /// </summary>
        internal static string ModelHeader {
            get {
                return ResourceManager.GetString("ModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Configurator.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Configuration.
        /// </summary>
        internal static string StartConfiguration {
            get {
                return ResourceManager.GetString("StartConfiguration", resourceCulture);
            }
        }
    }
}
