//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFZ_Konfigurator.Resources.Localization.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesHeader {
            get {
                return ResourceManager.GetString("AccessoriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesTitle {
            get {
                return ResourceManager.GetString("AccessoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistence Systems.
        /// </summary>
        internal static string AccessoryCategory_AssistenceSystems {
            get {
                return ResourceManager.GetString("AccessoryCategory_AssistenceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        internal static string AccessoryCategory_Comfort {
            get {
                return ResourceManager.GetString("AccessoryCategory_Comfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infotainment.
        /// </summary>
        internal static string AccessoryCategory_Infotainment {
            get {
                return ResourceManager.GetString("AccessoryCategory_Infotainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology and Safety.
        /// </summary>
        internal static string AccessoryCategory_TechnologyAndSafety {
            get {
                return ResourceManager.GetString("AccessoryCategory_TechnologyAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Configuration_GoToOverview {
            get {
                return ResourceManager.GetString("Configuration_GoToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design your individual car by configuring each and every part of it.
        /// </summary>
        internal static string ConfigurationDescription {
            get {
                return ResourceManager.GetString("ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        internal static string ConfigurationList {
            get {
                return ResourceManager.GetString("ConfigurationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        internal static string ConfigurationName_Placeholder {
            get {
                return ResourceManager.GetString("ConfigurationName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Data.
        /// </summary>
        internal static string ConfigurationOverview_TechnicalData_Header {
            get {
                return ResourceManager.GetString("ConfigurationOverview_TechnicalData_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Configuration.
        /// </summary>
        internal static string ConfigurationOverviewHeader {
            get {
                return ResourceManager.GetString("ConfigurationOverviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Overview.
        /// </summary>
        internal static string ConfigurationOverviewTitle {
            get {
                return ResourceManager.GetString("ConfigurationOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        internal static string EngineSettingsHeader {
            get {
                return ResourceManager.GetString("EngineSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Settings.
        /// </summary>
        internal static string EngineSettingsTitle {
            get {
                return ResourceManager.GetString("EngineSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorHeader {
            get {
                return ResourceManager.GetString("ExteriorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string ExteriorTitle {
            get {
                return ResourceManager.GetString("ExteriorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string FuelKind_Diesel {
            get {
                return ResourceManager.GetString("FuelKind_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        internal static string FuelKind_Petrol {
            get {
                return ResourceManager.GetString("FuelKind_Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string Gears {
            get {
                return ResourceManager.GetString("Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a link to your configuration.
        /// </summary>
        internal static string GenerateConfigurationLink_Label {
            get {
                return ResourceManager.GetString("GenerateConfigurationLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your model.
        /// </summary>
        internal static string ModelHeader {
            get {
                return ResourceManager.GetString("ModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        internal static string PaintsHeader {
            get {
                return ResourceManager.GetString("PaintsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Configurator.
        /// </summary>
        internal static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rims.
        /// </summary>
        internal static string RimsHeader {
            get {
                return ResourceManager.GetString("RimsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Configuration.
        /// </summary>
        internal static string StartConfiguration {
            get {
                return ResourceManager.GetString("StartConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration 0-100 km/h.
        /// </summary>
        internal static string TechnicalData_Acceleration {
            get {
                return ResourceManager.GetString("TechnicalData_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        internal static string TechnicalData_Consumption {
            get {
                return ResourceManager.GetString("TechnicalData_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissions.
        /// </summary>
        internal static string TechnicalData_Emissions {
            get {
                return ResourceManager.GetString("TechnicalData_Emissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Size.
        /// </summary>
        internal static string TechnicalData_EngineSize {
            get {
                return ResourceManager.GetString("TechnicalData_EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        internal static string TechnicalData_FuelType {
            get {
                return ResourceManager.GetString("TechnicalData_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Performance.
        /// </summary>
        internal static string TechnicalData_Performance {
            get {
                return ResourceManager.GetString("TechnicalData_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed.
        /// </summary>
        internal static string TechnicalData_TopSpeed {
            get {
                return ResourceManager.GetString("TechnicalData_TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string TechnicalData_Transmission {
            get {
                return ResourceManager.GetString("TechnicalData_Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Gear.
        /// </summary>
        internal static string TechnicalData_Transmission_LabelSuffix {
            get {
                return ResourceManager.GetString("TechnicalData_Transmission_LabelSuffix", resourceCulture);
            }
        }
    }
}
