//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum AccessorySubCategory : int
    {
        None = 0,
        Climate = 1,
        Locksystems = 2,
        Navigation = 3,
        Entertainment = 4,
        DrivingAndBrakes = 5,
        Mirror = 6
    }
}
