//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum AccessoryCategory : int
    {
        Transport = 0,
        Interior = 1,
        Exterior = 2,
        Entertainment = 3,
        Navigation = 4,
        Assistence = 5,
        Driving = 6
    }
}
