//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum BodyKind : int
    {
        Sportback = 0,
        Limousine = 1,
        Cabriolet = 2,
        Avant = 3,
        Coupé = 4,
        SUV = 5,
        Roadster = 6
    }
}
