//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum BodyKind : int
    {
        Saloon = 0,
        Cabrio = 1,
        Hatchback = 2,
        Estate = 3,
        Coupe = 4,
        SUV = 5
    }
}
