//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum CarBrandKind : int
    {
        BMW = 0,
        Audi = 1,
        Mercedes = 2,
        Ford = 3,
        Subaru = 4,
        Toyota = 5,
        Lexus = 6,
        VW = 7,
        Honda = 8,
        Peugeot = 9,
        Nissan = 10,
        Fiat = 11
    }
}
