//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarConfiguratorEntityContext : DbContext
    {
        public CarConfiguratorEntityContext()
            : base("name=CarConfiguratorEntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<EngineSettings> EngineSettings { get; set; }
        public virtual DbSet<Paint> Paints { get; set; }
        public virtual DbSet<Rim> Rims { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Engine> Engines { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    }
}
