//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Performance { get; set; }
        public double Acceleration { get; set; }
        public double Consumption { get; set; }
        public double Price { get; set; }
        public double EngineSize { get; set; }
        public int TopSpeed { get; set; }
        public int Emission { get; set; }
        public int FuelKind { get; set; }
    }
}
