//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFZ_Konfigurator.Models
{
    using System;
    
    public enum RimBrandKind : int
    {
        Vossen = 0,
        Enkei = 1,
        BBS = 2,
        OZRacing = 3,
        Konig = 4,
        SSR = 5,
        TSW = 6,
        Motegi = 7,
        Focal = 8,
        Lexani = 9,
        KMC = 10,
        ION = 11,
        Oxgord = 12
    }
}
